"""Adicionado coluna de ano de nascimento para Author

Revision ID: 3a8223ce7e49
Revises: c58bda830b9f
Create Date: 2026-06-12 14:26:45.047340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8223ce7e49'
down_revision: Union[str, Sequence[str], None] = 'c58bda830b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('birth_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'birth_year')
    # ### end Alembic commands ###
