"""Removendo a unicidade da coluna name de Author

Revision ID: 7b286728bda5
Revises: 3a8223ce7e49
Create Date: 2026-06-12 15:19:48.752753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b286728bda5'
down_revision: Union[str, Sequence[str], None] = '3a8223ce7e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
